services:
  - type: web
    name: ecommerce-website
    env: node
    buildCommand: |
      npm install
      npm run build
      mkdir -p server/build
      cp -r client/build/* server/build/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MODNO_DB
        sync: false
      - key: JWT
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
