services:
  - type: web
    name: ecommerce-website
    env: node
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
      cd ../server
      mkdir -p build
      cp -r ../client/build/* build/
      echo "Verifying build files..."
      ls -la build/
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MODNO_DB
        sync: false
      - key: JWT
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /api/products/
    autoDeploy: true
